/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SocialRouteImport } from './routes/social'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as GaiaRouteImport } from './routes/gaia'
import { Route as DualRouteImport } from './routes/dual'
import { Route as ControlRouteImport } from './routes/control'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SocialPostRouteImport } from './routes/social.post'

const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const GaiaRoute = GaiaRouteImport.update({
  id: '/gaia',
  path: '/gaia',
  getParentRoute: () => rootRouteImport,
} as any)
const DualRoute = DualRouteImport.update({
  id: '/dual',
  path: '/dual',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlRoute = ControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialPostRoute = SocialPostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => SocialRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/control': typeof ControlRoute
  '/dual': typeof DualRoute
  '/gaia': typeof GaiaRoute
  '/missions': typeof MissionsRoute
  '/onboarding': typeof OnboardingRoute
  '/scanner': typeof ScannerRoute
  '/simulator': typeof SimulatorRoute
  '/social': typeof SocialRouteWithChildren
  '/social/post': typeof SocialPostRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/control': typeof ControlRoute
  '/dual': typeof DualRoute
  '/gaia': typeof GaiaRoute
  '/missions': typeof MissionsRoute
  '/onboarding': typeof OnboardingRoute
  '/scanner': typeof ScannerRoute
  '/simulator': typeof SimulatorRoute
  '/social': typeof SocialRouteWithChildren
  '/social/post': typeof SocialPostRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/control': typeof ControlRoute
  '/dual': typeof DualRoute
  '/gaia': typeof GaiaRoute
  '/missions': typeof MissionsRoute
  '/onboarding': typeof OnboardingRoute
  '/scanner': typeof ScannerRoute
  '/simulator': typeof SimulatorRoute
  '/social': typeof SocialRouteWithChildren
  '/social/post': typeof SocialPostRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/control'
    | '/dual'
    | '/gaia'
    | '/missions'
    | '/onboarding'
    | '/scanner'
    | '/simulator'
    | '/social'
    | '/social/post'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/control'
    | '/dual'
    | '/gaia'
    | '/missions'
    | '/onboarding'
    | '/scanner'
    | '/simulator'
    | '/social'
    | '/social/post'
  id:
    | '__root__'
    | '/'
    | '/control'
    | '/dual'
    | '/gaia'
    | '/missions'
    | '/onboarding'
    | '/scanner'
    | '/simulator'
    | '/social'
    | '/social/post'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ControlRoute: typeof ControlRoute
  DualRoute: typeof DualRoute
  GaiaRoute: typeof GaiaRoute
  MissionsRoute: typeof MissionsRoute
  OnboardingRoute: typeof OnboardingRoute
  ScannerRoute: typeof ScannerRoute
  SimulatorRoute: typeof SimulatorRoute
  SocialRoute: typeof SocialRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaia': {
      id: '/gaia'
      path: '/gaia'
      fullPath: '/gaia'
      preLoaderRoute: typeof GaiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dual': {
      id: '/dual'
      path: '/dual'
      fullPath: '/dual'
      preLoaderRoute: typeof DualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control': {
      id: '/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof ControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/post': {
      id: '/social/post'
      path: '/post'
      fullPath: '/social/post'
      preLoaderRoute: typeof SocialPostRouteImport
      parentRoute: typeof SocialRoute
    }
  }
}

interface SocialRouteChildren {
  SocialPostRoute: typeof SocialPostRoute
}

const SocialRouteChildren: SocialRouteChildren = {
  SocialPostRoute: SocialPostRoute,
}

const SocialRouteWithChildren =
  SocialRoute._addFileChildren(SocialRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ControlRoute: ControlRoute,
  DualRoute: DualRoute,
  GaiaRoute: GaiaRoute,
  MissionsRoute: MissionsRoute,
  OnboardingRoute: OnboardingRoute,
  ScannerRoute: ScannerRoute,
  SimulatorRoute: SimulatorRoute,
  SocialRoute: SocialRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
